<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>MATH 140: Scatter plots and Linear Regression</title>

<script src="site_libs/header-attrs-2.19/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cosmo.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">MATH 140</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="slides.html">Slides</a>
</li>
<li>
  <a href="activities.html">Activities and Labs</a>
</li>
<li>
  <a href="data.html">Data</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    RStudio
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="rstudio.html">Installation and Orientation</a>
    </li>
    <li>
      <a href="basicstats.html">Data and Descriptive Statistics</a>
    </li>
    <li>
      <a href="dataviz.html">Data Visualization with ggplot</a>
    </li>
    <li>
      <a href="datamanip.html">Data Manipulation with dplyr</a>
    </li>
    <li>
      <a href="regression.html">Linear Regression</a>
    </li>
    <li>
      <a href="inference.html">Inference</a>
    </li>
    <li>
      <a href="references.html">Other Resources</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="mailto:&lt;mhitchm@linfield.edu&gt;">
    <span class="fa fa-envelope fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="http://github.com/mphitchman/stats">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">MATH 140: Scatter plots and Linear
Regression</h1>

</div>


<style type=text/css>
body{ /* Normal  */
      font-size: 14px;
  }
h1.title {
  font-size: 20px;
  color: DarkGreen;
}
h1 { /* Header 1 */
  font-size: 20px;
  color: DarkGreen;
}
h2 { /* Header 2 */
    font-size: 18px;
}
h3 { /* Header 3 */
  font-size: 17px;
}
blockquote {
    background: #f8f8f8;
    padding: 5px 10px;
    margin: 0 0 10px;
    font-size: 16px;
    border-left: 1px solid #aaa;
    border-bottom: 1px solid #aaa;
}
</style>
<div id="the-planets-data" class="section level1">
<h1>The planets data</h1>
<p>The following code creates a data frame with 3 variables (named
<em>planet</em>, <em>distance</em>, and <em>period</em>) and 9
observations. This data frame encodes information about the 9 planets in
the solar system.</p>
<pre class="r"><code>planets = data.frame(
  planet=c(&quot;Mercury&quot;,&quot;Venus&quot;,&quot;Earth&quot;,&quot;Mars&quot;,&quot;Jupiter&quot;,&quot;Saturn&quot;,&quot;Uranus&quot;,&quot;Neptune&quot;,&quot;Pluto&quot;),
  distance=c(36,67,93,142,484,887,1765,2791,3654),
  period=c(88, 225, 365, 687, 4332, 10760, 30684, 60188, 90467)
  )</code></pre>
<p>Notes about this code:</p>
<ul>
<li><code>planets</code> is the name of the data frame</li>
<li><code>data.frame()</code> is the command for creating a data
frame</li>
<li>the data frame has three columns named <code>planet</code>,
<code>distance</code>, and <code>period</code></li>
<li>the column entries are created with the <code>c()</code>
command.</li>
<li>the entries for a categorical variable such as the <em>planet</em>
variable are enclosed, individually, with quotes.</li>
<li>the units:
<ul>
<li><code>distance</code> is given in millions of miles from the
Sun</li>
<li><code>period</code> is given in Earth days (how long it takes the
planet to make one revolution around the Sun)</li>
</ul></li>
</ul>
</div>
<div id="making-a-scatter-plot" class="section level1">
<h1>Making a scatter plot</h1>
<p>We can make quick and clear scatter plots using the built-in R
command <code>plot()</code>, or higher quality plots using the package
<code>ggplot</code>.</p>
<div id="using-plot" class="section level2">
<h2>Using <code>plot()</code></h2>
<p>In the worksheet we choose <code>distance</code> to be the
explanatory variable (<span class="math inline">\(x\)</span>), and
<code>period</code> to be the response variable (<span
class="math inline">\(y\)</span>). The <code>plot()</code> command
produces a scatter plot:</p>
<pre class="r"><code>plot(x=planets$distance,y=planets$period)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-2-1.png" width="480" /></p>
<p>But we should make our graphs more user friendly by adding a plot
title and better axis labels:</p>
<pre class="r"><code>plot(x=planets$distance,y=planets$period,
     xlab=&quot;distance from sun (millions of miles)&quot;,
     ylab=&quot;period of revolution (earth days)&quot;,
     main=&quot;Planets in our solar system&quot;)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-3-1.png" width="480" /></p>
<p>We can even change the look of the points, as discussed in the <a
href="https://mphitchman.com/stats/basicstats.html#Scatter_plots">Data
and Descriptive Statistics Tutorial</a></p>
</div>
<div id="using-ggplot" class="section level2">
<h2>Using <code>ggplot()</code></h2>
<p>The <em>tidyverse</em> package (which you’ve already installed) comes
with an excellent graphics package called <em>ggplot</em>. If you load
the tidyverse into your RStudio session, you will be able to produce
graphics with <em>ggplot</em>.</p>
<p>To load the tidyverse into your session, run this line:</p>
<pre><code>library(tidyverse)</code></pre>
<p>With the tidyverse loaded, you are ready to use the ggplot functions
for generating graphs.</p>
<p><strong>Basic scatter plot with ggplot</strong></p>
<pre class="r"><code>ggplot(data = planets,aes(x=distance,y=period)) +
  geom_point()</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-4-1.png" width="480" /></p>
<p><strong>Adding color, labels, and changing themes.</strong></p>
<pre class="r"><code>ggplot(data = planets,aes(x=distance,y=period)) +
  geom_point(col=&quot;seagreen&quot;)+
  xlab(&quot;distance to Sun (millions of miles)&quot;) + 
  ylab(&quot;period of revolution (Earth days)&quot;) +
  ggtitle(&quot;Planets in the Solar System&quot;) + 
  theme_bw()</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-5-1.png" width="480" /></p>
</div>
<div id="the-correlation-coefficient" class="section level2">
<h2>The correlation coefficient</h2>
<p>We use the <code>cor()</code> command:</p>
<pre class="r"><code>cor(planets$distance,planets$period)</code></pre>
<pre><code>## [1] 0.9889708</code></pre>
</div>
</div>
<div id="the-least-squares-linear-model" class="section level1">
<h1>The least-squares linear model</h1>
<blockquote>
<p>Use the <code>lm()</code> command (“lm” stands for linear model).
Running <code>lm(y~x)</code> where y and x are specified columns in your
data frame will give the slope and <span
class="math inline">\(y\)</span>-intercept of the least-squares
regression line:</p>
</blockquote>
<pre class="r"><code>lm(planets$period~planets$distance)</code></pre>
<pre><code>## 
## Call:
## lm(formula = planets$period ~ planets$distance)
## 
## Coefficients:
##      (Intercept)  planets$distance  
##          -4578.8              24.1</code></pre>
<p>So, the slope of the least-squares line is 24.1 and the <span
class="math inline">\(y\)</span>-intercept is -4578.8.</p>
<p>Better yet, assign a name to the <code>lm()</code> command, like
<em>fit</em>, when you run it (as in the code below) and you have quick
access to all sorts of useful information:</p>
<pre class="r"><code>fit=lm(planets$period~planets$distance)</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">Command</th>
<th align="left">Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left"><code>fit$coefficients</code></td>
<td align="left"><span class="math inline">\(y\)</span>-intercept and
slope of least-squares line</td>
</tr>
<tr class="even">
<td align="left"><code>fit$residuals</code></td>
<td align="left">list of the residuals</td>
</tr>
<tr class="odd">
<td align="left"><code>fit$fitted.values</code></td>
<td align="left">list of the predicted values <span
class="math inline">\(\hat{y}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="plot-the-least-squares-line" class="section level1">
<h1>Plot the least-squares line</h1>
<div id="using-built-in-r-commands" class="section level2">
<h2>Using built-in R commands</h2>
<p>RStudio likes to describe the <span
class="math inline">\(y\)</span>-intercept and slope of a line with the
constants <span class="math inline">\(a\)</span> and <span
class="math inline">\(b\)</span>, respectively. As in <span
class="math display">\[y=a + bx,\]</span> and the command
<code>abline(a= ..., b=...)</code> will add a line with <span
class="math inline">\(y\)</span>-intercept <span
class="math inline">\(a\)</span> and slope <span
class="math inline">\(b\)</span> to a plot if you run these lines of
code in succession:</p>
<pre class="r"><code>plot(x=planets$distance,y=planets$period,
     xlab=&quot;distance from sun (millions of miles)&quot;,
     ylab=&quot;period of revolution&quot;,
     main=&quot;Planets in our solar system&quot;)
abline(a=-4578.8,b=24.1)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-9-1.png" width="480" /></p>
</div>
<div id="making-a-residual-plot" class="section level2">
<h2>Making a Residual Plot</h2>
<p>We can plot the <span class="math inline">\(x\)</span>-coordinates
against the residuals and add a dashed horizontal line through <span
class="math inline">\(y = 0\)</span> with this code</p>
<pre class="r"><code>plot(planets$distance,fit$residuals)
abline(h=0,lty=2,col=&quot;brown3&quot;)</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
</div>
<div id="in-ggplot" class="section level2">
<h2>In ggplot</h2>
<div id="with-the-geom_abline-command" class="section level3">
<h3>With the <code>geom_abline()</code> command</h3>
<p>Here are two approaches. The first adds the line with the
<code>geom_abline()</code> command by manually entering the slope and
y-intercept as found above:</p>
<pre class="r"><code>ggplot(data = planets,aes(x=distance,y=period)) +
  geom_point(col=&quot;seagreen&quot;) +
  xlab(&quot;distance to Sun (millions of miles)&quot;) + 
  ylab(&quot;period of revolution (Earth days)&quot;) +
  ggtitle(&quot;Planets in the Solar System&quot;) + 
  geom_abline(slope = 24.1, intercept = -4578.8,col=&quot;dodgerblue&quot;)+
  theme_bw()</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-11-1.png" width="480" /></p>
</div>
<div id="using-geom_smooth" class="section level3">
<h3>Using geom_smooth()</h3>
<p>The second approach to fitting a line to data is to use the
<code>geom_smooth()</code>command. The advantage here is that the code
generates the line from scratch - you don’t have to manually enter the
slope and <span class="math inline">\(y\)</span>-intercept.</p>
<pre class="r"><code>ggplot(data = planets,aes(x=distance,y=period)) +
  geom_point(col=&quot;seagreen&quot;)+
  xlab(&quot;distance to Sun (millions of miles)&quot;) + 
  ylab(&quot;period of revolution (Earth days)&quot;) +
  ggtitle(&quot;Planets in the Solar System&quot;) + 
  geom_smooth(method=&#39;lm&#39;, formula=y~x, col=&quot;blue&quot;,size=.8,se=FALSE) +
  theme_classic()</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-12-1.png" width="480" /></p>
<p>Notice the new “classic” theme!</p>
</div>
</div>
</div>
<div id="bonus-round-a-better-model" class="section level1">
<h1>Bonus Round: A Better Model</h1>
<p>The residual plot makes clear that, even though the correlation
coefficient is very close to 1, a curved model is better, one that can
be represented by a polynomial with a higher power of <span
class="math inline">\(x\)</span>.</p>
<p>To find the nature of the curved fit, we begin by comparing
<code>log(x)</code> to <code>log(y)</code>.</p>
<p><strong>Intermission: Logarithms</strong></p>
<p>Recall, <span class="math inline">\(\log_{10}(x)\)</span> = the power
we need to raise 10 to in order to get <span
class="math inline">\(x\)</span>. For instance, <span
class="math inline">\(\log_{10}(100) = 2\)</span> since 10^2 = 100$,
<span class="math inline">\(\log_{10}(1000) = 3\)</span>, <span
class="math inline">\(\log_10(1,000,000) = 6\)</span>, and <span
class="math inline">\(\log_{10}(0.1)=-1\)</span> since <span
class="math inline">\(10^{-1} = \frac{1}{10}=0.1\)</span>.</p>
<p><strong>End of Intermission</strong></p>
<p>So, again, to find the nature of the curved fit, we begin by
comparing <code>log(x)</code> to <code>log(y)</code>, and see whether
the association is linear.</p>
<pre class="r"><code>ggplot(data=planets,aes(log10(distance),log10(period)))+
  geom_point()+
  ggtitle(&quot;Plotting log(distance) vs log(period)&quot;)+
  theme_bw()</code></pre>
<p><img src="regression_files/figure-html/unnamed-chunk-13-1.png" width="480" /></p>
<p>Does this plot look linear?</p>
<p><em>Heck yeah!</em> Super linear, in fact.</p>
<!--

```r
cor(log10(planets$distance),log10(planets$period))
```

```
## [1] 0.9999978
```

And the residual plot!


```r
# Create the log-log linear model
logfit=lm(log10(planets$period)~log10(planets$distance))
# Plot the x-coordinates against the residuals)
plot(log10(planets$distance),logfit$residuals)
abline(h=0,lty=2,col="brown3")
```

<img src="regression_files/figure-html/unnamed-chunk-15-1.png" width="672" />

Looks linear to me!!

-->
<p>If the log-log plot is linear, then the slope of the least-squares
line for the log-log data will equal the power in the curved fit for
<span class="math inline">\(y\)</span> and <span
class="math inline">\(x\)</span>.</p>
<pre class="r"><code>logfit=lm(log10(planets$period)~log10(planets$distance))
logfit$coefficients</code></pre>
<pre><code>##             (Intercept) log10(planets$distance) 
##              -0.3922215               1.5013054</code></pre>
<p>Notice the slope of this linear model is about 1.5, and this explains
why we chose the <span class="math inline">\(x^{1.5}\)</span> for the
curved fit in the last question of the R Regression activity.</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
